eureka:
  client:
    register-with-eureka: false
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 9999
spring:
  application:
    name: Gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: delivery-tracker-route
              uri: lb://delivery-tracker/
              predicates:
                - Path=/api/v1/deliveries/**
                - Method=GET,POST,PUT,DELETE,OPTIONS #optional
            - id: courier-manager-route
              uri: lb://courier-manager/
              predicates:
                - Path=/api/v1/couriers/**